@product=http://localhost:3000/product

###
GET {{product}} HTTP/1.1

###

POST {{product}} HTTP/1.1
content-type: application/json

{
    "name": "net",
    "image": "bouch",
    "likes": 6
}


###
GET {{product}}/1 HTTP/1.1