version: '1'

services:
  
  server:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - postgres_db
    command: ['npm', 'start']
  
  postgres_db:
    image: postgres:9.6-alpine
    env_file: ./.env
    ports:
      - 5433:5432
    volumes:
      - ./database:/var/lib/postgresql/data
volumes:
  database:
